hop/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include


from app import views, projects, jobtypes, customers, users, reports, works, properties, codes

urlpatterns = [

    # ADMIN
    url(r'^admin/', admin.site.urls),

    # INDEX (Dashboard)
    url(r'^$', views.index, name='dashboard'),

    # LOGIN
    url(r'^login$', views.login_user, name='login'),

    # LOGOUT
    url(r'^logout$', views.logout_user, name='logout'),

    # PROJECTS
    url(r'^projects$', projects.views, name='projects'),

    # PROPERTIES
    url(r'^properties$', properties.views, name='properties'),

    # JOB TYPES
    url(r'^jobtypes$', jobtypes.views, name='jobtypes'),

    # JOB REQUESTS
    url(r'^job_requests$', views.job_requests, name='job_requests'),

    # CUSTOMERS
    url(r'^customers$', customers.views, name='customers'),

    # USERS
    url(r'^users$', users.views, name='users'),

    # STATS
    url(r'^reports$', reports.views, name='reports'),

    # WORKS
    url(r'^works$', works.views, name='works'),

    # WORK CODES
    url(r'^codes$', codes.views, name='codes'),

    # APIs Colors
    url(r'^set_color_hoe_header$', views.set_color_hoe_header, name='set_color_hoe_header'),
    url(r'^set_color_hoe_right_header$', views.set_color_hoe_right_header, name='set_color_hoe_right_header'),
    url(r'^set_color_hoeapp_container$', views.set_color_hoeapp_container, name='set_color_hoeapp_container'),

    # APIs
    url(r'^api/', include('rest.urls'), name='apis'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/forms.py
import os
from django import forms

from app.functions import USER_GROUP_TECHNICIAN_ID, USERS_GROUPS, PROJECTS_GROUPS
from app.models import Projects, Customers, Users


class ExtFileField(forms.FileField):
    """
    * max_upload_size - a number indicating the maximum file size allowed for upload.
            500Kb - 524288
            1MB - 1048576
            2.5MB - 2621440
            5MB - 5242880
            10MB - 10485760
            20MB - 20971520
            50MB - 5242880
            100MB 104857600
            250MB - 214958080
            500MB - 429916160
    t = ExtFileField(ext_whitelist=(".pdf", ".txt"), max_upload_size=)
    """

    def __init__(self, *args, **kwargs):
        ext_whitelist = kwargs.pop("ext_whitelist")
        self.ext_whitelist = [i.lower() for i in ext_whitelist]
        self.max_upload_size = kwargs.pop("max_upload_size")
        super(ExtFileField, self).__init__(*args, **kwargs)

    def clean(self, *args, **kwargs):
        upload = super(ExtFileField, self).clean(*args, **kwargs)
        if upload:
            size = upload.size
            filename = upload.name
            ext = os.path.splitext(filename)[1]
            ext = ext.lower()

            if size == 0 or ext not in self.ext_whitelist or size > self.max_upload_size:
                raise forms.ValidationError("Tipo de fichero o tamanno no permitido!")


class ProjectsForm(forms.Form):
    name = forms.CharField(max_length=200, required=True, label='Name')
    grupo = forms.ChoiceField(choices=PROJECTS_GROUPS, label='Group', required=True,
                              widget=forms.Select(attrs={'class': 'imp-50'}))


class PropertiesForm(forms.Form):
    project = forms.ModelChoiceField(Projects.objects, label='Project', required=False)
    name = forms.CharField(max_length=300, label='Name')


class JobTypesForm(forms.Form):
    name = forms.CharField(max_length=200, required=True, label='Name')


class InstallationsCodesForm(forms.Form):
    code = forms.CharField(max_length=10, required=True, label='Code', widget=forms.TextInput(attrs={'class': 'imp-30'}))
    description = forms.CharField(max_length=200, required=False, label='Description')
    price = forms.FloatField(initial='0.00', required=False, label='Price', widget=forms.TextInput(attrs={'class': 'imp-30'}))
    scope = forms.CharField(required=False, label='Scopes (separated by commas)', widget=forms.Textarea(attrs={'cols': '2', 'rows': '5'}))


class CustomersForm(forms.Form):
    is_company = forms.BooleanField(required=False, initial=True,
                                    label='Is Company? (checked = Company. no checked = Customer)',
                                    widget=forms.CheckboxInput(attrs={'class': 'form-control'}))
    name = forms.CharField(max_length=300, required=True, label='Name')
    phone = forms.CharField(max_length=100, required=False, label='Phone')
    email = forms.CharField(max_length=300, required=False, label='Email')


class UsersForm(forms.Form):
    group = forms.ChoiceField(choices=USERS_GROUPS, label='Group', required=True, widget=forms.Select(attrs={'class': 'imp-50'}))
    username = forms.CharField(max_length=100, required=True, label='Username', widget=forms.TextInput(attrs={'class': 'imp-50'}))
    first_name = forms.CharField(max_length=300, required=True, label='FirstName')
    last_name = forms.CharField(max_length=300, required=True, label='LastName')
    email = forms.CharField(max_length=300, required=False, label='Email')
    phone = forms.CharField(max_length=100, required=False, label='Phone',
                            widget=forms.TextInput(attrs={'class': 'imp-50'}))
    avatar = ExtFileField(label='Avatar', help_text='Max size allowed 5Mb in jpeg, jpg, gif, png format',
                          required=False, ext_whitelist=(".jpeg", ".jpg", ".gif", ".png"), max_upload_size=5242880)
    password = forms.CharField(max_length=300, required=False, label='Password',
                               widget=forms.PasswordInput(attrs={'class': 'imp-100'}))


class WorksForm(forms.Form):
    # Customer Data
    customer = forms.ModelChoiceField(Customers.objects.order_by('name'), label='Customer',
                                      required=False, widget=forms.Select(attrs={'class': 'imp-75 myselect2',
                                                                                 'separator': 'Select Customer or Create New Customer'}))
    customer_name = forms.CharField(max_length=300, required=False, label='Customer Name',
                                    widget=forms.TextInput(attrs={'class': 'form-control imp-75'}))
    customer_email = forms.CharField(max_length=300, required=False, label='Customer Email',
                                     widget=forms.TextInput(attrs={'class': 'form-control imp-75'}))
    customer_phone = forms.CharField(max_length=100, required=False, label='Customer Phone',
                                     widget=forms.TextInput(attrs={'class': 'form-control imp-30'}))

    # Works Details
    # project = forms.ModelChoiceField(Projects.objects.order_by('name'), label='Project',
    #                                  required=True, widget=forms.Select(attrs={'class': 'imp-75 myselect2',
    #                                                                            'separator': 'Work Details'}))
    # property = forms.ModelChoiceField(Properties.objects.order_by('name'), label='Property',
    #                                   required=False, widget=forms.Select(attrs={'class': 'imp-75 myselect2'}))
    address = forms.CharField(required=False, label='Address', widget=forms.Textarea(attrs={'rows': '2', 'cols': '2',
                                                                                            'class': 'form-control'}))
    date = forms.CharField(required=False, label='Date', widget=forms.TextInput(attrs={'class': 'imp-20',
                                                                                       'placeholder': 'mm-dd-yyyy'}))
    initial_time = forms.CharField(required=False, label='Start Time', widget=forms.TextInput(attrs={'class': 'imp-20',
                                                                                                     'placeholder': 'hh:mm'}))
    feedback_email = forms.CharField(required=False, label='Feedback Email', widget=forms.TextInput(attrs={'class': 'imp-100'}))
    notes = forms.CharField(required=False, label='Notes', widget=forms.Textarea(attrs={'rows': '3', 'cols': '2',
                                                                                        'class': 'form-control'}))
    # Wor Team
    leader = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
                                    widget=forms.Select(attrs={'class': 'imp-50 myselect2',
                                                               'separator': 'Work Team'}), label='Leader')
    support1 = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
                                      widget=forms.Select(attrs={'class': 'imp-50 myselect2'}), label='Support 1')
    support2 = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
                                      widget=forms.Select(attrs={'class': 'imp-50 myselect2'}), label='Support 2')
    support3 = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
                                      widget=forms.Select(attrs={'class': 'imp-50 myselect2'}), label='Support 3')
    # support4 = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
    #                                   widget=forms.Select(attrs={'class': 'imp-50 myselect2'}), label='Support 4')
    # support5 = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
    #                                   widget=forms.Select(attrs={'class': 'imp-50 myselect2'}), label='Support 5')


class ChangeAddressForm(forms.Form):
    address = forms.CharField(required=False, label='Address',
                              widget=forms.Textarea(attrs={'rows': '2', 'cols': '2', 'class': 'form-control'}))


class NewLeaderForm(forms.Form):
    leader = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
                                    widget=forms.Select(attrs={'class': 'imp-50'}), label='Leader')
    support1 = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
                                      widget=forms.Select(attrs={'class': 'imp-50'}), label='Support 1')
    support2 = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
                                      widget=forms.Select(attrs={'class': 'imp-50'}), label='Support 2')
    support3 = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
                                      widget=forms.Select(attrs={'class': 'imp-50'}), label='Support 3')
    # support4 = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
    #                                 widget=forms.Select(attrs={'class': 'imp-50'}), label='Support 4')
    # support5 = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
    #                                 widget=forms.Select(attrs={'class': 'imp-50'}), label='Support 5')


class ImportXLSForm(forms.Form):
    file = ExtFileField(label='Select Excel File', help_text='Max size allowed 4Mb (extensions: xls, xlsx)',
                        ext_whitelist=(".xls", ".xlsx"), max_upload_size=4194304, required=False)

templates/customers/add.html
{% extends "forms.html" %}

{% block extraheading %}
    <style>

        .checkbox-company{
            float: left;
            width: 25px;
            margin-right: 1em!important;
            margin-top: -5px!important;
        }

    </style>

    <script>

        $("#customers").addClass("active");
        $("#id_name").focus();

        $("#id_is_company").parent().addClass('checkbox-company');

    </script>
{% endblock %}

{% block form-title %}{{ title }}{% endblock %}
{% block form-action %}{% url 'customers' %}{% endblock %}
{% block form-extra %}
    <input type='hidden' name='action' value='add'/>
{% endblock %}
{% block form-back %}{% url 'customers' %}{% endblock %}

templates/customers/delete.html
{% extends "forms.html" %}

{% block extraheading %}
    <script>
        $("#customers").addClass("active");
    </script>
{% endblock %}

{% block form-title %}{{ title }}{% endblock %}
{% block form-action %}{% url 'customers' %}{% endblock %}
{% block form-extra %}
    <input type='hidden' name='action' value='delete'/>
    <input type='hidden' name='id' value='{{ customer.id }}'/>
{% endblock %}
{% block form-back %}{% url 'customers' %}{% endblock %}
{% block form-object %}{{ customer }}{% endblock %}
{% block buttonname %}YES{% endblock %}
{% block buttoncancel %}NO{% endblock %}

templates/customers/edit.html
{% extends "forms.html" %}

{% block extraheading %}

    <style>

        .checkbox-company{
            float: left;
            width: 25px;
            margin-right: 1em!important;
            margin-top: -5px!important;
        }

    </style>

    <script>

        $("#customers").addClass("active");
        $("#id_name").focus();

        $("#id_is_company").parent().addClass('checkbox-company');

    </script>

{% endblock %}

{% block form-title %}{{ title }}{% endblock %}
{% block form-action %}{% url 'customers' %}{% endblock %}
{% block form-extra %}
    <input type='hidden' name='action' value='edit'/>
    <input type='hidden' name='id' value='{{ customer.id }}'/>
{% endblock %}
{% block form-back %}{% url 'customers' %}{% endblock %}

templates/customers/view.html
{% extends 'base.html' %}

{% block heading %}

    <script>

        $("#customers").addClass("active");

    </script>
{% endblock %}

{% block canvas %}
    <div class="container-fluid">
        <div class="row margin-row">
            <p class="myheading"> <i class="fa fa-users"></i> {{ title }}</p>
            <table class="table table-bordered table-hover">
                <thead>
                <tr style="font-weight: bold; font-size: 1.1em; background-color: #043b8a; color: white">
                    <th style="width: 70px">Type</th>
                    <th>Name</th>
                    <th style="width: 250px">Email</th>
                    <th style="width: 150px">Phone</th>
                    <th style="width: 60px" class="text-center">Works</th>
                    <th style="width: 60px" class="text-center">Comp.</th>
                    <th style="width: 60px" class="text-center">Incom.</th>
                    <th style="width: 60px" class="text-center">Created</th>
                    <th style="width: 70px"></th>
                </tr>
                </thead>
                <tbody>
                {% for c in customers %}
                    <tr>
                        <td class="font11">
                            {% if c.is_company %}
                                <label class="label label-success">Company</label>
                            {% else %}
                                <label class="label label-info">Customer</label>
                            {% endif %}
                        </td>
                        <td class="font14">{{ c.name }}</td>
                        <td class="font12">{{ c.email }}</td>
                        <td class="font12">{{ c.phone }}</td>
                        <td class="text-center font14">{{ c.get_number_works|floatformat:0 }}</td>
                        <td class="text-center font14">{{ c.get_number_works_completed|floatformat:0 }}</td>
                        <td class="text-center font14">{{ c.get_number_works_incompleted|floatformat:0 }}</td>
                        <td class="text-center font11">{{ c.created_at|date:'m-d-Y' }}</td>
                        <td class="text-center">
                            {% ifnotequal c.id customer_create_new_customer_id %}
                                <a class="tu" href="{% url 'customers' %}?action=edit&id={{ c.id }}" title="Edit"><i class="fa fa-pencil"></i></a>
{#                                {% if not c.has_relations %}#}
                                    <a class="tu" href="{% url 'customers' %}?action=delete&id={{ c.id }}" title="Delete" style="margin-left: 0.4em"><i class="fa fa-times"></i></a>
{#                                {% endif %}#}
                            {% endifnotequal %}
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="10" class="alert alert-info">
                            <i>There are not customers in the system. Click in the <strong>+ Add Customer</strong> button to add your first customer</i>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

            <div class="row">
                <div class="col-sm-6">
                    <a class="btn btn-success" href="{% url 'customers' %}?action=add"><i class="fa fa-plus"></i> Add Customer</a>
                </div>
                <div class="col-sm-6 text-right">
                    {% if paging.num_pages > 20 %}
                        <ul class="pagination">
                            {% if paging.first_page %}
                                <li><a href="{%  url 'customers' %}?page=1{% if search %}&s={{ search }}{% endif %}">1</a></li>
                                <li><a href="{%  url 'customers' %}?page={{ paging.ellipsis_left}}{% if search %}&s={{ search }}{% endif %}"
                                       class="active">...</a></li>
                            {% endif %}
                            {% for pagenumber in paging.pages %}
                                <li {% ifequal pagenumber page.number %}class='active'{% endifequal %}>
                                    <a href="{%  url 'customers' %}?page={{ pagenumber }}{% if search %}&s={{ search }}{% endif %}">
                                        {{ pagenumber }}
                                    </a>
                                </li>
                            {% endfor %}
                            {% if paging.last_page %}
                                <li>
                                    <a href="{%  url 'customers' %}?page={{ paging.ellipsis_right }}{% if search %}&s={{ search }}{% endif %}"
                                       class="active">
                                        ...
                                    </a>
                                </li>
                                <li>
                                    <a href="{%  url 'customers' %}?page={{ paging.num_pages }}{% if search %}&s={{ search }}{% endif %}">
                                        {{ paging.num_pages }}
                                    </a>
                                </li>
                            {% endif %}
                        </ul>
                    {% else %}
                        <ul class='pagination pagination-sm'>
                            {% for pagenumber in paging.page_range %}
                                <li {% ifequal pagenumber page.number %}class='active'{% endifequal %}>
                                    <a href="{%  url 'customers' %}?page={{ pagenumber }}{% if search %}&s={{ search }}{% endif %}">
                                        {{ pagenumber }}
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            </div>

        </div>
    </div>
{% endblock %}