hop/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include


from app import views, projects, jobtypes, customers, users, reports, works, properties, codes

urlpatterns = [

    # ADMIN
    url(r'^admin/', admin.site.urls),

    # INDEX (Dashboard)
    url(r'^$', views.index, name='dashboard'),

    # LOGIN
    url(r'^login$', views.login_user, name='login'),

    # LOGOUT
    url(r'^logout$', views.logout_user, name='logout'),

    # PROJECTS
    url(r'^projects$', projects.views, name='projects'),

    # PROPERTIES
    url(r'^properties$', properties.views, name='properties'),

    # JOB TYPES
    url(r'^jobtypes$', jobtypes.views, name='jobtypes'),

    # JOB REQUESTS
    url(r'^job_requests$', views.job_requests, name='job_requests'),

    # CUSTOMERS
    url(r'^customers$', customers.views, name='customers'),

    # USERS
    url(r'^users$', users.views, name='users'),

    # STATS
    url(r'^reports$', reports.views, name='reports'),

    # WORKS
    url(r'^works$', works.views, name='works'),

    # WORK CODES
    url(r'^codes$', codes.views, name='codes'),

    # APIs Colors
    url(r'^set_color_hoe_header$', views.set_color_hoe_header, name='set_color_hoe_header'),
    url(r'^set_color_hoe_right_header$', views.set_color_hoe_right_header, name='set_color_hoe_right_header'),
    url(r'^set_color_hoeapp_container$', views.set_color_hoeapp_container, name='set_color_hoeapp_container'),

    # APIs
    url(r'^api/', include('rest.urls'), name='apis'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/forms.py
import os
from django import forms

from app.functions import USER_GROUP_TECHNICIAN_ID, USERS_GROUPS, PROJECTS_GROUPS
from app.models import Projects, Customers, Users


class ExtFileField(forms.FileField):
    """
    * max_upload_size - a number indicating the maximum file size allowed for upload.
            500Kb - 524288
            1MB - 1048576
            2.5MB - 2621440
            5MB - 5242880
            10MB - 10485760
            20MB - 20971520
            50MB - 5242880
            100MB 104857600
            250MB - 214958080
            500MB - 429916160
    t = ExtFileField(ext_whitelist=(".pdf", ".txt"), max_upload_size=)
    """

    def __init__(self, *args, **kwargs):
        ext_whitelist = kwargs.pop("ext_whitelist")
        self.ext_whitelist = [i.lower() for i in ext_whitelist]
        self.max_upload_size = kwargs.pop("max_upload_size")
        super(ExtFileField, self).__init__(*args, **kwargs)

    def clean(self, *args, **kwargs):
        upload = super(ExtFileField, self).clean(*args, **kwargs)
        if upload:
            size = upload.size
            filename = upload.name
            ext = os.path.splitext(filename)[1]
            ext = ext.lower()

            if size == 0 or ext not in self.ext_whitelist or size > self.max_upload_size:
                raise forms.ValidationError("Tipo de fichero o tamanno no permitido!")


class ProjectsForm(forms.Form):
    name = forms.CharField(max_length=200, required=True, label='Name')
    grupo = forms.ChoiceField(choices=PROJECTS_GROUPS, label='Group', required=True,
                              widget=forms.Select(attrs={'class': 'imp-50'}))


class PropertiesForm(forms.Form):
    project = forms.ModelChoiceField(Projects.objects, label='Project', required=False)
    name = forms.CharField(max_length=300, label='Name')


class JobTypesForm(forms.Form):
    name = forms.CharField(max_length=200, required=True, label='Name')


class InstallationsCodesForm(forms.Form):
    code = forms.CharField(max_length=10, required=True, label='Code', widget=forms.TextInput(attrs={'class': 'imp-30'}))
    description = forms.CharField(max_length=200, required=False, label='Description')
    price = forms.FloatField(initial='0.00', required=False, label='Price', widget=forms.TextInput(attrs={'class': 'imp-30'}))
    scope = forms.CharField(required=False, label='Scopes (separated by commas)', widget=forms.Textarea(attrs={'cols': '2', 'rows': '5'}))


class CustomersForm(forms.Form):
    is_company = forms.BooleanField(required=False, initial=True,
                                    label='Is Company? (checked = Company. no checked = Customer)',
                                    widget=forms.CheckboxInput(attrs={'class': 'form-control'}))
    name = forms.CharField(max_length=300, required=True, label='Name')
    phone = forms.CharField(max_length=100, required=False, label='Phone')
    email = forms.CharField(max_length=300, required=False, label='Email')


class UsersForm(forms.Form):
    group = forms.ChoiceField(choices=USERS_GROUPS, label='Group', required=True, widget=forms.Select(attrs={'class': 'imp-50'}))
    username = forms.CharField(max_length=100, required=True, label='Username', widget=forms.TextInput(attrs={'class': 'imp-50'}))
    first_name = forms.CharField(max_length=300, required=True, label='FirstName')
    last_name = forms.CharField(max_length=300, required=True, label='LastName')
    email = forms.CharField(max_length=300, required=False, label='Email')
    phone = forms.CharField(max_length=100, required=False, label='Phone',
                            widget=forms.TextInput(attrs={'class': 'imp-50'}))
    avatar = ExtFileField(label='Avatar', help_text='Max size allowed 5Mb in jpeg, jpg, gif, png format',
                          required=False, ext_whitelist=(".jpeg", ".jpg", ".gif", ".png"), max_upload_size=5242880)
    password = forms.CharField(max_length=300, required=False, label='Password',
                               widget=forms.PasswordInput(attrs={'class': 'imp-100'}))


class WorksForm(forms.Form):
    # Customer Data
    customer = forms.ModelChoiceField(Customers.objects.order_by('name'), label='Customer',
                                      required=False, widget=forms.Select(attrs={'class': 'imp-75 myselect2',
                                                                                 'separator': 'Select Customer or Create New Customer'}))
    customer_name = forms.CharField(max_length=300, required=False, label='Customer Name',
                                    widget=forms.TextInput(attrs={'class': 'form-control imp-75'}))
    customer_email = forms.CharField(max_length=300, required=False, label='Customer Email',
                                     widget=forms.TextInput(attrs={'class': 'form-control imp-75'}))
    customer_phone = forms.CharField(max_length=100, required=False, label='Customer Phone',
                                     widget=forms.TextInput(attrs={'class': 'form-control imp-30'}))

    # Works Details
    # project = forms.ModelChoiceField(Projects.objects.order_by('name'), label='Project',
    #                                  required=True, widget=forms.Select(attrs={'class': 'imp-75 myselect2',
    #                                                                            'separator': 'Work Details'}))
    # property = forms.ModelChoiceField(Properties.objects.order_by('name'), label='Property',
    #                                   required=False, widget=forms.Select(attrs={'class': 'imp-75 myselect2'}))
    address = forms.CharField(required=False, label='Address', widget=forms.Textarea(attrs={'rows': '2', 'cols': '2',
                                                                                            'class': 'form-control'}))
    date = forms.CharField(required=False, label='Date', widget=forms.TextInput(attrs={'class': 'imp-20',
                                                                                       'placeholder': 'mm-dd-yyyy'}))
    initial_time = forms.CharField(required=False, label='Start Time', widget=forms.TextInput(attrs={'class': 'imp-20',
                                                                                                     'placeholder': 'hh:mm'}))
    feedback_email = forms.CharField(required=False, label='Feedback Email', widget=forms.TextInput(attrs={'class': 'imp-100'}))
    notes = forms.CharField(required=False, label='Notes', widget=forms.Textarea(attrs={'rows': '3', 'cols': '2',
                                                                                        'class': 'form-control'}))
    # Wor Team
    leader = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
                                    widget=forms.Select(attrs={'class': 'imp-50 myselect2',
                                                               'separator': 'Work Team'}), label='Leader')
    support1 = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
                                      widget=forms.Select(attrs={'class': 'imp-50 myselect2'}), label='Support 1')
    support2 = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
                                      widget=forms.Select(attrs={'class': 'imp-50 myselect2'}), label='Support 2')
    support3 = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
                                      widget=forms.Select(attrs={'class': 'imp-50 myselect2'}), label='Support 3')
    # support4 = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
    #                                   widget=forms.Select(attrs={'class': 'imp-50 myselect2'}), label='Support 4')
    # support5 = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
    #                                   widget=forms.Select(attrs={'class': 'imp-50 myselect2'}), label='Support 5')


class ChangeAddressForm(forms.Form):
    address = forms.CharField(required=False, label='Address',
                              widget=forms.Textarea(attrs={'rows': '2', 'cols': '2', 'class': 'form-control'}))


class NewLeaderForm(forms.Form):
    leader = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
                                    widget=forms.Select(attrs={'class': 'imp-50'}), label='Leader')
    support1 = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
                                      widget=forms.Select(attrs={'class': 'imp-50'}), label='Support 1')
    support2 = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
                                      widget=forms.Select(attrs={'class': 'imp-50'}), label='Support 2')
    support3 = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
                                      widget=forms.Select(attrs={'class': 'imp-50'}), label='Support 3')
    # support4 = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
    #                                 widget=forms.Select(attrs={'class': 'imp-50'}), label='Support 4')
    # support5 = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
    #                                 widget=forms.Select(attrs={'class': 'imp-50'}), label='Support 5')


class ImportXLSForm(forms.Form):
    file = ExtFileField(label='Select Excel File', help_text='Max size allowed 4Mb (extensions: xls, xlsx)',
                        ext_whitelist=(".xls", ".xlsx"), max_upload_size=4194304, required=False)

templates/users/add.html
{% extends "forms.html" %}

{% block extraheading %}
    <style>
        #id_group {
            height: 2.5em;
        }
    </style>
    <script>
        $("#users").addClass("active");
        $("#id_username").focus().css('text-transform', 'lowercase');
    </script>
{% endblock %}

{% block form-title %}{{ title }}{% endblock %}
{% block form-action %}{% url 'users' %}{% endblock %}
{% block form-extra %}
    <input type='hidden' name='action' value='add'/>
{% endblock %}
{% block form-back %}{% url 'users' %}{% endblock %}

templates/users/delete.html
{% extends "forms.html" %}

{% block extraheading %}
    <script>
        $("#users").addClass("active");
    </script>
{% endblock %}

{% block form-title %}{{ title }}{% endblock %}
{% block form-action %}{% url 'users' %}{% endblock %}
{% block form-extra %}
    <input type='hidden' name='action' value='delete'/>
    <input type='hidden' name='id' value='{{ theuser.id }}'/>
{% endblock %}
{% block form-back %}{% url 'users' %}{% endblock %}
{% block form-object %}{{ theuser.complete_name }}{% endblock %}
{% block buttonname %}YES{% endblock %}
{% block buttoncancel %}NO{% endblock %}

templates/users/edit.html
{% extends "forms.html" %}

{% block extraheading %}
    <style>
        #id_group {
            height: 2.5em;
        }
    </style>
    <script>
        $("#users").addClass("active");
        $("#id_username").focus().css('text-transform', 'lowercase');
    </script>
{% endblock %}

{% block form-title %}{{ title }}{% endblock %}
{% block form-action %}{% url 'users' %}{% endblock %}
{% block form-extra %}
    <input type='hidden' name='action' value='edit'/>
    <input type='hidden' name='id' value='{{ myuser.id }}'/>
{% endblock %}
{% block form-back %}{% url 'users' %}{% endblock %}

templates/users/view.html
{% extends 'base.html' %}
{% load static %}

{% block heading %}
    <script>
        $(".menu-principal").removeClass("active");
        $("#users").addClass("active");

        $("#btn-search").click(function () {
            var search = $('#input-search').val();
            if (search){
                location.href = "{% url 'users' %}?s="+search;
            }
        });

        $('#input-search').keyup(function(e) {
            if(e.keyCode === 13) {
                $("#btn-search").trigger("click");
            }
        });

    </script>
{% endblock %}

{% block canvas %}
    <div class="container-fluid">
        <div class="row margin-row">

            <div class="col-sm-8">
                <a class="btn btn-success tu" href="{% url 'users' %}?action=add" title="Add User">
                    <i class="fa fa-plus"></i>
                </a>
                <span class="myheading">
                    {{ title }}
                </span>
            </div>

            <div class="col-sm-4 text-right">
                <form class="form-inline">
                    <div class="form-group">
                        <label class="sr-only" for="search"></label>
                        <div class="input-group">
                            <input class="form-control" id="input-search" placeholder="Search users" value="{% if search %}{{ search }}{% endif %}">
                        </div>
                    </div>
                    <a id="btn-search" class="btn btn-info" title="Search"><i class="fa fa-search"></i></a>
                    {% if search %}<a href="{% url 'users' %}" class="btn btn-info" title="All"><i class="fa fa-list-alt"></i></a>{% endif %}
                </form>
            </div>
        </div>

        <div class="row margin-row">
            <table class="table table-bordered table-hover">
                <thead>
                <tr style="font-weight: bold; font-size: 1em; background-color: #043b8a; color: white">
                    <th style="width: 80px" class="text-center"></th>
                    <th style="width: 150px">User</th>
                    <th>Name</th>
                    <th style="width: 250px">Email</th>
                    <th style="width: 100px" class="text-center">Phone</th>
                    <th style="width: 50px" class="text-center">Works</th>
                    <th style="width: 50px" class="text-center">Comp.</th>
                    <th style="width: 50px" class="text-center">Incomp.</th>
                    <th style="width: 80px" class="text-center">Created</th>
                    <th style="width: 80px"></th>
                </tr>
                </thead>
                <tbody>
                {% for u in users %}
                    <tr>
                        <td class="text-center">
                            {% if u.avatar %}
                                <img class="main" src="{{ u.download_avatar }}" width="40px" height="40px"/>
                            {% else %}
                                <img class="main" src="{% static 'images/avatar.png' %}" width="40px" height="40px" />
                            {% endif %}
                        </td>
                        <td class="my-vertical-align font12">
                            {{ u.user.username }}
                            <br/><span class="label label-info" style="font-size: 0.7em">{{ u.user_group_name }}</span>
                        </td>
                        <td class="my-vertical-align font12">{{ u.user.first_name }} {{ u.user.last_name }}</td>
                        <td class="my-vertical-align font12">{{ u.user.email }}</td>
                        <td class="my-vertical-align font12">{{ u.phone|default_if_none:'' }}</td>
                        <td class="my-vertical-align text-center font14">
                            {{ u.get_number_works|floatformat:0 }}
                        </td>
                        <td class="my-vertical-align text-center font14">
                            {{ u.get_number_works_completed|floatformat:0 }}
                        </td>
                        <td class="my-vertical-align text-center font14">
                            {{ u.get_number_works_incompleted|floatformat:0 }}
                        </td>
                        <td class="my-vertical-align text-center font12">{{ u.created_at|date:'m-d-Y' }}</td>
                        <td class="my-vertical-align text-center">
                            <a class="tu" href="{% url 'users' %}?action=edit&id={{ u.id }}" title="Edit"><i class="fa fa-pencil"></i></a>
{#                            {% if not u.has_relations %}#}
                                <a class="tu" href="{% url 'users' %}?action=delete&id={{ u.id }}" title="Delete" style="margin-left: 0.2em"><i class="fa fa-times"></i></a>
{#                            {% endif %}#}
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="10" class="alert alert-info">
                            <i>There are not users in the system. Click in the <strong>+ Add User</strong> button to add your first user</i>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
{% endblock %}