hop/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include


from app import views, projects, jobtypes, customers, users, reports, works, properties, codes

urlpatterns = [

    # ADMIN
    url(r'^admin/', admin.site.urls),

    # INDEX (Dashboard)
    url(r'^$', views.index, name='dashboard'),

    # LOGIN
    url(r'^login$', views.login_user, name='login'),

    # LOGOUT
    url(r'^logout$', views.logout_user, name='logout'),

    # PROJECTS
    url(r'^projects$', projects.views, name='projects'),

    # PROPERTIES
    url(r'^properties$', properties.views, name='properties'),

    # JOB TYPES
    url(r'^jobtypes$', jobtypes.views, name='jobtypes'),

    # JOB REQUESTS
    url(r'^job_requests$', views.job_requests, name='job_requests'),

    # CUSTOMERS
    url(r'^customers$', customers.views, name='customers'),

    # USERS
    url(r'^users$', users.views, name='users'),

    # STATS
    url(r'^reports$', reports.views, name='reports'),

    # WORKS
    url(r'^works$', works.views, name='works'),

    # WORK CODES
    url(r'^codes$', codes.views, name='codes'),

    # APIs Colors
    url(r'^set_color_hoe_header$', views.set_color_hoe_header, name='set_color_hoe_header'),
    url(r'^set_color_hoe_right_header$', views.set_color_hoe_right_header, name='set_color_hoe_right_header'),
    url(r'^set_color_hoeapp_container$', views.set_color_hoeapp_container, name='set_color_hoeapp_container'),

    # APIs
    url(r'^api/', include('rest.urls'), name='apis'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/forms.py
import os
from django import forms

from app.functions import USER_GROUP_TECHNICIAN_ID, USERS_GROUPS, PROJECTS_GROUPS
from app.models import Projects, Customers, Users


class ExtFileField(forms.FileField):
    """
    * max_upload_size - a number indicating the maximum file size allowed for upload.
            500Kb - 524288
            1MB - 1048576
            2.5MB - 2621440
            5MB - 5242880
            10MB - 10485760
            20MB - 20971520
            50MB - 5242880
            100MB 104857600
            250MB - 214958080
            500MB - 429916160
    t = ExtFileField(ext_whitelist=(".pdf", ".txt"), max_upload_size=)
    """

    def __init__(self, *args, **kwargs):
        ext_whitelist = kwargs.pop("ext_whitelist")
        self.ext_whitelist = [i.lower() for i in ext_whitelist]
        self.max_upload_size = kwargs.pop("max_upload_size")
        super(ExtFileField, self).__init__(*args, **kwargs)

    def clean(self, *args, **kwargs):
        upload = super(ExtFileField, self).clean(*args, **kwargs)
        if upload:
            size = upload.size
            filename = upload.name
            ext = os.path.splitext(filename)[1]
            ext = ext.lower()

            if size == 0 or ext not in self.ext_whitelist or size > self.max_upload_size:
                raise forms.ValidationError("Tipo de fichero o tamanno no permitido!")


class ProjectsForm(forms.Form):
    name = forms.CharField(max_length=200, required=True, label='Name')
    grupo = forms.ChoiceField(choices=PROJECTS_GROUPS, label='Group', required=True,
                              widget=forms.Select(attrs={'class': 'imp-50'}))


class PropertiesForm(forms.Form):
    project = forms.ModelChoiceField(Projects.objects, label='Project', required=False)
    name = forms.CharField(max_length=300, label='Name')


class JobTypesForm(forms.Form):
    name = forms.CharField(max_length=200, required=True, label='Name')


class InstallationsCodesForm(forms.Form):
    code = forms.CharField(max_length=10, required=True, label='Code', widget=forms.TextInput(attrs={'class': 'imp-30'}))
    description = forms.CharField(max_length=200, required=False, label='Description')
    price = forms.FloatField(initial='0.00', required=False, label='Price', widget=forms.TextInput(attrs={'class': 'imp-30'}))
    scope = forms.CharField(required=False, label='Scopes (separated by commas)', widget=forms.Textarea(attrs={'cols': '2', 'rows': '5'}))


class CustomersForm(forms.Form):
    is_company = forms.BooleanField(required=False, initial=True,
                                    label='Is Company? (checked = Company. no checked = Customer)',
                                    widget=forms.CheckboxInput(attrs={'class': 'form-control'}))
    name = forms.CharField(max_length=300, required=True, label='Name')
    phone = forms.CharField(max_length=100, required=False, label='Phone')
    email = forms.CharField(max_length=300, required=False, label='Email')


class UsersForm(forms.Form):
    group = forms.ChoiceField(choices=USERS_GROUPS, label='Group', required=True, widget=forms.Select(attrs={'class': 'imp-50'}))
    username = forms.CharField(max_length=100, required=True, label='Username', widget=forms.TextInput(attrs={'class': 'imp-50'}))
    first_name = forms.CharField(max_length=300, required=True, label='FirstName')
    last_name = forms.CharField(max_length=300, required=True, label='LastName')
    email = forms.CharField(max_length=300, required=False, label='Email')
    phone = forms.CharField(max_length=100, required=False, label='Phone',
                            widget=forms.TextInput(attrs={'class': 'imp-50'}))
    avatar = ExtFileField(label='Avatar', help_text='Max size allowed 5Mb in jpeg, jpg, gif, png format',
                          required=False, ext_whitelist=(".jpeg", ".jpg", ".gif", ".png"), max_upload_size=5242880)
    password = forms.CharField(max_length=300, required=False, label='Password',
                               widget=forms.PasswordInput(attrs={'class': 'imp-100'}))


class WorksForm(forms.Form):
    # Customer Data
    customer = forms.ModelChoiceField(Customers.objects.order_by('name'), label='Customer',
                                      required=False, widget=forms.Select(attrs={'class': 'imp-75 myselect2',
                                                                                 'separator': 'Select Customer or Create New Customer'}))
    customer_name = forms.CharField(max_length=300, required=False, label='Customer Name',
                                    widget=forms.TextInput(attrs={'class': 'form-control imp-75'}))
    customer_email = forms.CharField(max_length=300, required=False, label='Customer Email',
                                     widget=forms.TextInput(attrs={'class': 'form-control imp-75'}))
    customer_phone = forms.CharField(max_length=100, required=False, label='Customer Phone',
                                     widget=forms.TextInput(attrs={'class': 'form-control imp-30'}))

    # Works Details
    # project = forms.ModelChoiceField(Projects.objects.order_by('name'), label='Project',
    #                                  required=True, widget=forms.Select(attrs={'class': 'imp-75 myselect2',
    #                                                                            'separator': 'Work Details'}))
    # property = forms.ModelChoiceField(Properties.objects.order_by('name'), label='Property',
    #                                   required=False, widget=forms.Select(attrs={'class': 'imp-75 myselect2'}))
    address = forms.CharField(required=False, label='Address', widget=forms.Textarea(attrs={'rows': '2', 'cols': '2',
                                                                                            'class': 'form-control'}))
    date = forms.CharField(required=False, label='Date', widget=forms.TextInput(attrs={'class': 'imp-20',
                                                                                       'placeholder': 'mm-dd-yyyy'}))
    initial_time = forms.CharField(required=False, label='Start Time', widget=forms.TextInput(attrs={'class': 'imp-20',
                                                                                                     'placeholder': 'hh:mm'}))
    feedback_email = forms.CharField(required=False, label='Feedback Email', widget=forms.TextInput(attrs={'class': 'imp-100'}))
    notes = forms.CharField(required=False, label='Notes', widget=forms.Textarea(attrs={'rows': '3', 'cols': '2',
                                                                                        'class': 'form-control'}))
    # Wor Team
    leader = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
                                    widget=forms.Select(attrs={'class': 'imp-50 myselect2',
                                                               'separator': 'Work Team'}), label='Leader')
    support1 = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
                                      widget=forms.Select(attrs={'class': 'imp-50 myselect2'}), label='Support 1')
    support2 = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
                                      widget=forms.Select(attrs={'class': 'imp-50 myselect2'}), label='Support 2')
    support3 = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
                                      widget=forms.Select(attrs={'class': 'imp-50 myselect2'}), label='Support 3')
    # support4 = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
    #                                   widget=forms.Select(attrs={'class': 'imp-50 myselect2'}), label='Support 4')
    # support5 = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
    #                                   widget=forms.Select(attrs={'class': 'imp-50 myselect2'}), label='Support 5')


class ChangeAddressForm(forms.Form):
    address = forms.CharField(required=False, label='Address',
                              widget=forms.Textarea(attrs={'rows': '2', 'cols': '2', 'class': 'form-control'}))


class NewLeaderForm(forms.Form):
    leader = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
                                    widget=forms.Select(attrs={'class': 'imp-50'}), label='Leader')
    support1 = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
                                      widget=forms.Select(attrs={'class': 'imp-50'}), label='Support 1')
    support2 = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
                                      widget=forms.Select(attrs={'class': 'imp-50'}), label='Support 2')
    support3 = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
                                      widget=forms.Select(attrs={'class': 'imp-50'}), label='Support 3')
    # support4 = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
    #                                 widget=forms.Select(attrs={'class': 'imp-50'}), label='Support 4')
    # support5 = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
    #                                 widget=forms.Select(attrs={'class': 'imp-50'}), label='Support 5')


class ImportXLSForm(forms.Form):
    file = ExtFileField(label='Select Excel File', help_text='Max size allowed 4Mb (extensions: xls, xlsx)',
                        ext_whitelist=(".xls", ".xlsx"), max_upload_size=4194304, required=False)

templates/works/add.html
{% extends "forms.html" %}

{% block extraheading %}
    <style>

        #id_project, #id_customer {
            height: 2.5em;
        }

        textarea {
            resize: none;
        }
    </style>
    <script>

        $("#works").addClass("active");

        $("#id_date").mask('00-00-0000').datepicker({format:"mm-dd-yyyy"}).on('changeDate', function(ev){ $(this).datepicker('hide');});

        $('#id_initial_time').mask('00:00');

        {#$('#id_property').empty();#}

        {#$("#id_project").change(function () {#}
        {##}
        {#    var elem = $('#id_property');#}
        {#    var projectid = $(this).val();#}
        {##}
        {#    elem.empty().append('<option value="">---------</option>').val(0);#}
        {#    if (projectid){#}
        {#        $.ajax({#}
        {#            type: "POST",#}
        {#            url: "{% url 'works' %}",#}
        {#            data: {'action': 'get_properties_from_project', 'pid': projectid},#}
        {#            success: function (data) {#}
        {#                if (data.result === 'ok') {#}
        {#                    for (var i in data.lista) {#}
        {#                        elem.append('<option value="' + data.lista[i][0] + '">' + data.lista[i][1] + '</option>');#}
        {#                    }#}
        {#                } else {#}
        {#                    alert(data.message);#}
        {#                }#}
        {#            },#}
        {#            error: function () {#}
        {#                alert("Server error");#}
        {#            },#}
        {#            dataType: "json"#}
        {#        });#}
        {#    }#}
        {##}
        {# });#}

        show_new_customers_elements = function () {
            $("#id_customer_name").parent().parent().show();
            $("#id_customer_email").parent().parent().show();
            $("#id_customer_phone").parent().parent().show();
        };

        hide_new_customers_elements = function () {
            $("#id_customer_name").parent().parent().hide();
            $("#id_customer_email").parent().parent().hide();
            $("#id_customer_phone").parent().parent().hide();
        };

        // Inicialization of new customers data (by default)
        hide_new_customers_elements();

        $("#id_customer").change(function () {
           var customer_id = $(this).val();
           if (customer_id){
               if (customer_id === '{{ customer_create_new_customer_id }}'){
                   show_new_customers_elements();
               }else{
                   hide_new_customers_elements();
               }
           }else{
               alert('Please Select one of the customer options');
               hide_new_customers_elements();
           }
        });

    </script>
{% endblock %}

{% block form-title %}{{ title }}{% endblock %}
{% block form-action %}{% url 'works' %}{% endblock %}
{% block form-width %}form-m{% endblock %}

{% block form-extra %}
    <input type='hidden' name='action' value='add'/>
{% endblock %}
{% block form-back %}{% url 'works' %}{% endblock %}

templates/works/change_address.html
{% extends "forms.html" %}

{% block extraheading %}
    <style>

        textarea {
            resize: none;
        }

    </style>
    <script>

        $("#works").addClass("active");

    </script>
{% endblock %}

{% block form-title %}{{ title }}{% endblock %}
{% block form-action %}{% url 'works' %}{% endblock %}
{% block form-width %}form-m{% endblock %}

{% block form-extra %}
    <input type='hidden' name='action' value='change_address'/>
    <input type='hidden' name='id' value='{{ work.id }}'/>
{% endblock %}
{% block form-back %}{% url 'works' %}{% endblock %}

templates/works/delete.html
{% extends "forms.html" %}

{% block extraheading %}
    <script>
        $("#works").addClass("active");
    </script>
{% endblock %}

{% block form-title %}{{ title }}{% endblock %}
{% block form-action %}{% url 'works' %}{% endblock %}
{% block form-extra %}
    <input type='hidden' name='action' value='delete'/>
    <input type='hidden' name='id' value='{{ work.id }}'/>
{% endblock %}
{% block form-back %}{% url 'works' %}{% endblock %}
{% block form-object %}{{ work }}{% endblock %}
{% block buttonname %}YES{% endblock %}
{% block buttoncancel %}NO{% endblock %}

templates/works/edit.html
{% extends "forms.html" %}

{% block extraheading %}
    <style>

        #id_project, #id_customer {
            height: 2.5em;
        }

        textarea {
            resize: none;
        }
    </style>
    <script>

        $("#works").addClass("active");

        $("#id_date").mask('00-00-0000').datepicker({format:"mm-dd-yyyy"}).on('changeDate', function(ev){ $(this).datepicker('hide');});

        $('#id_initial_time').mask('00:00');

        $('#id_property').empty();

        $("#id_project").change(function () {

            var elem = $('#id_property');
            var projectid = $(this).val();

            elem.empty().append('<option value="">---------</option>').val(0);
            if (projectid){
                $.ajax({
                    type: "POST",
                    url: "{% url 'works' %}",
                    data: {'action': 'get_properties_from_project', 'pid': projectid},
                    success: function (data) {
                        if (data.result === 'ok') {
                            for (var i in data.lista) {
                                elem.append('<option value="' + data.lista[i][0] + '">' + data.lista[i][1] + '</option>');
                            }
                        } else {
                            alert(data.message);
                        }
                    },
                    error: function () {
                        alert("Server error");
                    },
                    dataType: "json"
                });
            }

        });

        show_new_customers_elements = function () {
            $("#id_customer_name").parent().parent().show();
            $("#id_customer_email").parent().parent().show();
            $("#id_customer_phone").parent().parent().show();
        };

        hide_new_customers_elements = function () {
            $("#id_customer_name").parent().parent().hide();
            $("#id_customer_email").parent().parent().hide();
            $("#id_customer_phone").parent().parent().hide();
        };

        // Inicialization of new customers data (by default)
        hide_new_customers_elements();

        $("#id_customer").change(function () {
           var customer_id = $(this).val();
           if (customer_id){
               if (customer_id === '{{ customer_create_new_customer_id }}'){
                   show_new_customers_elements();
               }else{
                   hide_new_customers_elements();
               }
           }else{
               alert('Please Select one of the customer options');
               hide_new_customers_elements();
           }
        });

    </script>
{% endblock %}

{% block form-title %}{{ title }}{% endblock %}
{% block form-action %}{% url 'works' %}{% endblock %}
{% block form-width %}form-m{% endblock %}

{% block form-extra %}
    <input type='hidden' name='action' value='edit'/>
    <input type='hidden' name='id' value='{{ work.id }}'/>
{% endblock %}
{% block form-back %}{% url 'works' %}{% endblock %}

templates/works/import.html
{% extends "forms.html" %}
{% load static %}
{% block extraheading %}
    <script>
        $(function(){
            $("#id_file").addClass("validate[required]");
        });
    </script>
{% endblock %}

{% block form-title %}
    {{ title }}
    <div style="text-align: right">
        <a href="{% static 'images/hotwire_template.xlsx' %}"
           class="btn btn-success btn-sm tr"
           title="Download the excel template with the required fields you need to import your works to the hop system automatically">
            <i class="fa fa-download"></i> Download Template
        </a>
    </div>
{% endblock %}
{% block form-action %}{% url 'works' %}{% endblock %}
{% block form-width %}form-s{% endblock %}
{% block form-extra %}
    <input type='hidden' name='action' value='import'/>
{% endblock %}
{% block form-back %}{% url 'works' %}{% endblock %}

templates/works/invoice.html
{% extends "easy_pdf/base.html" %}
{% load static %}
{% load humanize %}

{% block layout_style %}
    <style type="text/css" xmlns:pdf="http://www.w3.org/1999/html">
        @page {
            margin-left: 1cm;
            margin-right: 1cm;
            margin-top: 1cm;
            margin-bottom: 1cm;
        }

        .page-break{
            page-break-after: always;
        }

        .table-border-gray {
            border: 2px solid lightgrey;
        }

        .tr-header {
            height: 40px;
            text-align: center;
        }

        .td-header {
            background-color: red;
            color: white;
            text-align: center;
            font-weight: bold;
        }

        .td-info {
            font-size: 1.2em;
            padding-top:0.3em;
            text-align: center;
        }

        .td-info-value {
            font-size: 1.5em;
            padding-top:0.3em;
            text-align: center;
        }

        .td-info-header {
            font-size: 1.7em;
            padding-top:0.3em;
            text-align: center;
        }

        .td-bold {
            font-weight: bold;
        }

        .tr-for-text-400 {
            height: 400px;
        }

        .tr-for-text-100 {
            height: 100px;
        }

        .tr-for-text-40 {
            height: 40px;
        }

    </style>

{% endblock %}

{% block content %}

    <table>

        <tr>
            <td style="width: 60%">
                <img src="{{ logo_invoice }}" width="400px" height="230px" />
            </td>
            <td style="width: 40%">

                <table class="table-border-gray">
                    <tr class="tr-header">
                        <td class="td-header">Date</td>
                        <td class="td-header">Invoice</td>
                    </tr>

                    <tr class="tr-header">
                        <td class="td-info-value">{{ work.date|date:'m-d-Y' }}</td>
                        <td class="td-info-header">{{ work.id }}</td>
                    </tr>
                </table>

            </td>
        </tr>

    </table>

    <br/>

    <table>

        <tr>
            <td style="width: 45%;">
                <table class="table-border-gray">
                    <tr class="tr-header">
                        <td class="td-header">Bill To</td>
                    </tr>
                    <tr class="tr-for-text-100">
                        <td class="td-info-header">{{ work.customer.name }}</td>
                    </tr>
                </table>
            </td>

            <td style="width: 10%"></td>

            <td style="width: 45%">
                <table class="table-border-gray">
                    <tr class="tr-header">
                        <td class="td-header">Pay To</td>
                    </tr>
                    <tr class="tr-for-text-100">
                        <td style="text-align: center">
                            <h4>HOP CONTRACTING INC.</h4>
                            <p>671 WEST 18TH STREET, HIALEAH, FL, 33010</p>
                            <p>TEL: (305) 902-6700</p>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>

    </table>

    <br/>

    <table>

        <tr>

            <td style="width: 25%;">
                <table class="table-border-gray">
                    <tr class="tr-header">
                        <td class="td-header">Project</td>
                    </tr>
                    <tr class="tr-for-text-40">
                        <td class="td-info-value">{{ work.project.name }}</td>
                    </tr>
                </table>
            </td>

            <td style="width: 5%"></td>

            <td style="width: 20%">
                <table class="table-border-gray">
                    <tr class="tr-header">
                        <td class="td-header">Terms</td>
                    </tr>
                    <tr class="tr-for-text-40">
                        <td class="td-info-value">Net 30</td>
                    </tr>
                </table>
            </td>

            <td style="width: 5%"></td>

            <td style="width: 20%">
                <table class="table-border-gray">
                    <tr class="tr-header">
                        <td class="td-header">Type</td>
                    </tr>
                    <tr class="tr-for-text-40">
                        <td class="td-info-value">OPS</td>
                    </tr>
                </table>
            </td>

            <td style="width: 5%"></td>

            <td style="width: 25%">
                <table class="table-border-gray">
                    <tr class="tr-header">
                        <td class="td-header">Purchasing Contact</td>
                    </tr>
                    <tr class="tr-for-text-40">
                        <td class="td-info-value">{{ work.created_by.user.first_name }} {{ work.created_by.user.last_name }}</td>
                    </tr>
                </table>
            </td>

        </tr>

    </table>

    <br/>

    <table>

        <tr>
            <td style="width: 20%;">
                <table class="table-border-gray">
                    <tr class="tr-header">
                        <td class="td-header">Items</td>
                    </tr>
                    <tr class="tr-for-text-400">
                        <td class="td-info">{{ work.get_installation_code_by_report.code }}</td>
                    </tr>
                </table>
            </td>

            <td style="width: 35%">
                <table class="table-border-gray">
                    <tr class="tr-header">
                        <td class="td-header">Description</td>
                    </tr>
                    <tr class="tr-for-text-400">
                        <td class="td-info">
                            <p>{{ work.get_installation_code_by_report.description }}</p>
                            <h4>Scope</h4>
                            <p>{{ work.get_installation_code_by_report.scope }}</p>
                            <h4>Address</h4>
                            <p>{{ work.address }}</p>
                        </td>
                    </tr>
                </table>
            </td>

            <td style="width: 15%">
                <table class="table-border-gray">
                    <tr class="tr-header">
                        <td class="td-header">Qty</td>
                    </tr>
                    <tr class="tr-for-text-400">
                        <td class="td-info-header">1</td>
                    </tr>
                </table>
            </td>

            <td style="width: 15%">
                <table class="table-border-gray">
                    <tr class="tr-header">
                        <td class="td-header">Rate</td>
                    </tr>
                    <tr class="tr-for-text-400">
                        <td class="td-info-value">{{ work.get_installation_code_by_report.price|floatformat:2|intcomma }}</td>
                    </tr>
                </table>
            </td>

            <td style="width: 15%">
                <table class="table-border-gray">
                    <tr class="tr-header">
                        <td class="td-header">Amount</td>
                    </tr>
                    <tr class="tr-for-text-400">
                        <td class="td-info-value">{{ work.get_installation_code_by_report.price|floatformat:2|intcomma }}</td>
                    </tr>
                </table>
            </td>

        </tr>

        <tr style="border: 2px solid lightgrey" class="tr-header">
            <td colspan="4"></td>
            <td class="td-info-value td-bold">$ {{ work.get_installation_code_by_report.price|floatformat:2|intcomma }}</td>
        </tr>

    </table>

    <br/>
    <br/>
    <br/>
    <br/>

    <p style="text-align: center">
        <a href="https://www.hopcontracting.net" style="text-decoration: none; color: #0e0e19"> www.hopcontracting.net</a>
    </p>

{% endblock %}

templates/works/newteam.html
{% extends "forms.html" %}

{% block extraheading %}
    <style>
        #id_leader {
            height: 2.5em;
        }
    </style>
    <script>
        $("#works").addClass("active");
    </script>
{% endblock %}

{% block form-title %}{{ title }}{% endblock %}
{% block form-action %}{% url 'works' %}{% endblock %}
{% block form-width %}form-m{% endblock %}

{% block form-extra %}
    <input type='hidden' name='action' value='newteam'/>
    <input type='hidden' name='id' value='{{ work.id }}'/>
{% endblock %}
{% block form-back %}{% url 'works' %}{% endblock %}