hop/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include


from app import views, projects, jobtypes, customers, users, reports, works, properties, codes

urlpatterns = [

    # ADMIN
    url(r'^admin/', admin.site.urls),

    # INDEX (Dashboard)
    url(r'^$', views.index, name='dashboard'),

    # LOGIN
    url(r'^login$', views.login_user, name='login'),

    # LOGOUT
    url(r'^logout$', views.logout_user, name='logout'),

    # PROJECTS
    url(r'^projects$', projects.views, name='projects'),

    # PROPERTIES
    url(r'^properties$', properties.views, name='properties'),

    # JOB TYPES
    url(r'^jobtypes$', jobtypes.views, name='jobtypes'),

    # JOB REQUESTS
    url(r'^job_requests$', views.job_requests, name='job_requests'),

    # CUSTOMERS
    url(r'^customers$', customers.views, name='customers'),

    # USERS
    url(r'^users$', users.views, name='users'),

    # STATS
    url(r'^reports$', reports.views, name='reports'),

    # WORKS
    url(r'^works$', works.views, name='works'),

    # WORK CODES
    url(r'^codes$', codes.views, name='codes'),

    # APIs Colors
    url(r'^set_color_hoe_header$', views.set_color_hoe_header, name='set_color_hoe_header'),
    url(r'^set_color_hoe_right_header$', views.set_color_hoe_right_header, name='set_color_hoe_right_header'),
    url(r'^set_color_hoeapp_container$', views.set_color_hoeapp_container, name='set_color_hoeapp_container'),

    # APIs
    url(r'^api/', include('rest.urls'), name='apis'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/forms.py
import os
from django import forms

from app.functions import USER_GROUP_TECHNICIAN_ID, USERS_GROUPS, PROJECTS_GROUPS
from app.models import Projects, Customers, Users


class ExtFileField(forms.FileField):
    """
    * max_upload_size - a number indicating the maximum file size allowed for upload.
            500Kb - 524288
            1MB - 1048576
            2.5MB - 2621440
            5MB - 5242880
            10MB - 10485760
            20MB - 20971520
            50MB - 5242880
            100MB 104857600
            250MB - 214958080
            500MB - 429916160
    t = ExtFileField(ext_whitelist=(".pdf", ".txt"), max_upload_size=)
    """

    def __init__(self, *args, **kwargs):
        ext_whitelist = kwargs.pop("ext_whitelist")
        self.ext_whitelist = [i.lower() for i in ext_whitelist]
        self.max_upload_size = kwargs.pop("max_upload_size")
        super(ExtFileField, self).__init__(*args, **kwargs)

    def clean(self, *args, **kwargs):
        upload = super(ExtFileField, self).clean(*args, **kwargs)
        if upload:
            size = upload.size
            filename = upload.name
            ext = os.path.splitext(filename)[1]
            ext = ext.lower()

            if size == 0 or ext not in self.ext_whitelist or size > self.max_upload_size:
                raise forms.ValidationError("Tipo de fichero o tamanno no permitido!")


class ProjectsForm(forms.Form):
    name = forms.CharField(max_length=200, required=True, label='Name')
    grupo = forms.ChoiceField(choices=PROJECTS_GROUPS, label='Group', required=True,
                              widget=forms.Select(attrs={'class': 'imp-50'}))


class PropertiesForm(forms.Form):
    project = forms.ModelChoiceField(Projects.objects, label='Project', required=False)
    name = forms.CharField(max_length=300, label='Name')


class JobTypesForm(forms.Form):
    name = forms.CharField(max_length=200, required=True, label='Name')


class InstallationsCodesForm(forms.Form):
    code = forms.CharField(max_length=10, required=True, label='Code', widget=forms.TextInput(attrs={'class': 'imp-30'}))
    description = forms.CharField(max_length=200, required=False, label='Description')
    price = forms.FloatField(initial='0.00', required=False, label='Price', widget=forms.TextInput(attrs={'class': 'imp-30'}))
    scope = forms.CharField(required=False, label='Scopes (separated by commas)', widget=forms.Textarea(attrs={'cols': '2', 'rows': '5'}))


class CustomersForm(forms.Form):
    is_company = forms.BooleanField(required=False, initial=True,
                                    label='Is Company? (checked = Company. no checked = Customer)',
                                    widget=forms.CheckboxInput(attrs={'class': 'form-control'}))
    name = forms.CharField(max_length=300, required=True, label='Name')
    phone = forms.CharField(max_length=100, required=False, label='Phone')
    email = forms.CharField(max_length=300, required=False, label='Email')


class UsersForm(forms.Form):
    group = forms.ChoiceField(choices=USERS_GROUPS, label='Group', required=True, widget=forms.Select(attrs={'class': 'imp-50'}))
    username = forms.CharField(max_length=100, required=True, label='Username', widget=forms.TextInput(attrs={'class': 'imp-50'}))
    first_name = forms.CharField(max_length=300, required=True, label='FirstName')
    last_name = forms.CharField(max_length=300, required=True, label='LastName')
    email = forms.CharField(max_length=300, required=False, label='Email')
    phone = forms.CharField(max_length=100, required=False, label='Phone',
                            widget=forms.TextInput(attrs={'class': 'imp-50'}))
    avatar = ExtFileField(label='Avatar', help_text='Max size allowed 5Mb in jpeg, jpg, gif, png format',
                          required=False, ext_whitelist=(".jpeg", ".jpg", ".gif", ".png"), max_upload_size=5242880)
    password = forms.CharField(max_length=300, required=False, label='Password',
                               widget=forms.PasswordInput(attrs={'class': 'imp-100'}))


class WorksForm(forms.Form):
    # Customer Data
    customer = forms.ModelChoiceField(Customers.objects.order_by('name'), label='Customer',
                                      required=False, widget=forms.Select(attrs={'class': 'imp-75 myselect2',
                                                                                 'separator': 'Select Customer or Create New Customer'}))
    customer_name = forms.CharField(max_length=300, required=False, label='Customer Name',
                                    widget=forms.TextInput(attrs={'class': 'form-control imp-75'}))
    customer_email = forms.CharField(max_length=300, required=False, label='Customer Email',
                                     widget=forms.TextInput(attrs={'class': 'form-control imp-75'}))
    customer_phone = forms.CharField(max_length=100, required=False, label='Customer Phone',
                                     widget=forms.TextInput(attrs={'class': 'form-control imp-30'}))

    # Works Details
    # project = forms.ModelChoiceField(Projects.objects.order_by('name'), label='Project',
    #                                  required=True, widget=forms.Select(attrs={'class': 'imp-75 myselect2',
    #                                                                            'separator': 'Work Details'}))
    # property = forms.ModelChoiceField(Properties.objects.order_by('name'), label='Property',
    #                                   required=False, widget=forms.Select(attrs={'class': 'imp-75 myselect2'}))
    address = forms.CharField(required=False, label='Address', widget=forms.Textarea(attrs={'rows': '2', 'cols': '2',
                                                                                            'class': 'form-control'}))
    date = forms.CharField(required=False, label='Date', widget=forms.TextInput(attrs={'class': 'imp-20',
                                                                                       'placeholder': 'mm-dd-yyyy'}))
    initial_time = forms.CharField(required=False, label='Start Time', widget=forms.TextInput(attrs={'class': 'imp-20',
                                                                                                     'placeholder': 'hh:mm'}))
    feedback_email = forms.CharField(required=False, label='Feedback Email', widget=forms.TextInput(attrs={'class': 'imp-100'}))
    notes = forms.CharField(required=False, label='Notes', widget=forms.Textarea(attrs={'rows': '3', 'cols': '2',
                                                                                        'class': 'form-control'}))
    # Wor Team
    leader = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
                                    widget=forms.Select(attrs={'class': 'imp-50 myselect2',
                                                               'separator': 'Work Team'}), label='Leader')
    support1 = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
                                      widget=forms.Select(attrs={'class': 'imp-50 myselect2'}), label='Support 1')
    support2 = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
                                      widget=forms.Select(attrs={'class': 'imp-50 myselect2'}), label='Support 2')
    support3 = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
                                      widget=forms.Select(attrs={'class': 'imp-50 myselect2'}), label='Support 3')
    # support4 = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
    #                                   widget=forms.Select(attrs={'class': 'imp-50 myselect2'}), label='Support 4')
    # support5 = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
    #                                   widget=forms.Select(attrs={'class': 'imp-50 myselect2'}), label='Support 5')


class ChangeAddressForm(forms.Form):
    address = forms.CharField(required=False, label='Address',
                              widget=forms.Textarea(attrs={'rows': '2', 'cols': '2', 'class': 'form-control'}))


class NewLeaderForm(forms.Form):
    leader = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
                                    widget=forms.Select(attrs={'class': 'imp-50'}), label='Leader')
    support1 = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
                                      widget=forms.Select(attrs={'class': 'imp-50'}), label='Support 1')
    support2 = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
                                      widget=forms.Select(attrs={'class': 'imp-50'}), label='Support 2')
    support3 = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
                                      widget=forms.Select(attrs={'class': 'imp-50'}), label='Support 3')
    # support4 = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
    #                                 widget=forms.Select(attrs={'class': 'imp-50'}), label='Support 4')
    # support5 = forms.ModelChoiceField(Users.objects.filter(group=USER_GROUP_TECHNICIAN_ID), required=False,
    #                                 widget=forms.Select(attrs={'class': 'imp-50'}), label='Support 5')


class ImportXLSForm(forms.Form):
    file = ExtFileField(label='Select Excel File', help_text='Max size allowed 4Mb (extensions: xls, xlsx)',
                        ext_whitelist=(".xls", ".xlsx"), max_upload_size=4194304, required=False)

templates/codes/add.html
{% extends "forms.html" %}

{% block extraheading %}
    <script>

        $("#codes").addClass("active");
        $("#id_code").focus();

        $("#id_price").blur(function () {
            numerico($(this), 0, 99999999999, 2);
        });

        $('textarea').click(function () {
            $(this).css('resize', 'none');
        });

    </script>
{% endblock %}

{% block form-title %}{{ title }}{% endblock %}
{% block form-action %}{% url 'codes' %}{% endblock %}
{% block form-extra %}
    <input type='hidden' name='action' value='add'/>
{% endblock %}
{% block form-back %}{% url 'codes' %}{% endblock %}

templates/codes/delete.html
{% extends "forms.html" %}

{% block extraheading %}
    <script>
        $("#codes").addClass("active");
    </script>
{% endblock %}

{% block form-title %}{{ title }}{% endblock %}
{% block form-action %}{% url 'codes' %}{% endblock %}
{% block form-extra %}
    <input type='hidden' name='action' value='delete'/>
    <input type='hidden' name='id' value='{{ code.id }}'/>
{% endblock %}
{% block form-back %}{% url 'codes' %}{% endblock %}
{% block form-object %}{{ code }}{% endblock %}
{% block buttonname %}YES{% endblock %}
{% block buttoncancel %}NO{% endblock %}

templates/codes/edit.html
{% extends "forms.html" %}

{% block extraheading %}
    <script>

        $("#codes").addClass("active");
        $("#id_code").focus();

        $("#id_price").blur(function () {
            numerico($(this), 0, 99999999999, 2);
        });

        $('textarea').click(function () {
            $(this).css('resize', 'none');
        });

    </script>
{% endblock %}

{% block form-title %}{{ title }}{% endblock %}
{% block form-action %}{% url 'codes' %}{% endblock %}
{% block form-extra %}
    <input type='hidden' name='action' value='edit'/>
    <input type='hidden' name='id' value='{{ code.id }}'/>
{% endblock %}
{% block form-back %}{% url 'codes' %}{% endblock %}

templates/codes/print.html
{% extends "easy_pdf/base.html" %}
{% load static %}

{% block layout_style %}

    <style type="text/css" xmlns:pdf="http://www.w3.org/1999/html">
        @page {
            margin-left: 1cm;
            margin-right: 1cm;
            margin-top: 1cm;
            margin-bottom: 1cm;
        }

        .td-header {
            background-color: red;
            color: white;
            font-weight: bold;
        }

        .tr-header {
            height: 30px;
            margin-left: 1em;
        }

        .td-info {
            font-size: 1em;
            height: 35px;
            margin-left: 0.5em;
        }

        .td-info-scope {
            font-size: 0.8em;
            height: 35px;
            margin-left: 0.5em;
        }

        .td-info-code {
            font-size: 1.2em;
            height: 35px;
            font-weight: bold;
            margin-left: 0.5em;
        }

    </style>

{% endblock %}

{% block content %}

    <p style="text-align: right">{{ today|date:'m-d-Y' }}</p>

    <table>
        <tr>
            <td style="width: 60%">
                <img src="{{ logo_invoice }}" width="300px" height="180px" />
            </td>
        </tr>
    </table>

    <br/>

    <h1 style="text-align: center">WORK CODES - HOP</h1>

    <br/>

    <table class="table-border-gray" style="border: 1px solid lightgoldenrodyellow">
        <tr class="tr-header">
            <td class="td-header" style="width: 15%">Code</td>
            <td class="td-header" style="width: 25%">Description</td>
            <td class="td-header" style="width: 10%">Price</td>
            <td class="td-header" style="width: 50%">Scope</td>
        </tr>
        {% for code in codes %}
            <tr>
                <td class="td-info-code">{{ code.code }}</td>
                <td class="td-info">{{ code.description }}</td>
                <td class="td-info" style="text-align: center">$ {{ code.price|floatformat:2 }}</td>
                <td class="td-info-scope">{{ code.scope }}</td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}

templates/codes/view.html
{% extends 'base.html' %}
{% load humanize %}

{% block heading %}
    <script>

        $(".menu-principal").removeClass("active");

        $("#codes").addClass("active");

        $("#btn-search").click(function () {
            var search = $('#input-search').val();
            if (search){
                location.href = "{% url 'codes' %}?s="+search;
            }
        });

        $('#input-search').keyup(function(e) {
            if(e.keyCode === 13) {
                $("#btn-search").trigger("click");
            }
        });

    </script>
{% endblock %}

{% block canvas %}
    <div class="container-fluid">
        <div class="row margin-row">

            <div class="col-sm-8">
                <p class="myheading"> <i class="fa fa-list"></i> {{ title }}</p>
            </div>

            <div class="col-sm-4 text-right">
                <form class="form-inline">
                    <div class="form-group">
                        <label class="sr-only" for="search"></label>
                        <div class="input-group">
                            <input class="form-control" id="input-search" placeholder="Search by code" value="{% if search %}{{ search }}{% endif %}">
                        </div>
                    </div>
                    <a id="btn-search" class="btn btn-success" title="Search"><i class="fa fa-search"></i></a>
                    {% if search %}<a href="{% url 'codes' %}" class="btn btn-info" title="All"><i class="fa fa-list-alt"></i></a>{% endif %}
                </form>
            </div>
        </div>

        <div class="row margin-row">
            <table class="table table-bordered table-hover">
                <thead>
                <tr style="font-weight: bold; font-size: 1.1em; background-color: #043b8a; color: white">
                    <th style="width: 130px" class="text-center">Code</th>
                    <th style="width: 260px">Description</th>
                    <th style="width: 100px" class="text-center">Price</th>
                    <th>Scope</th>
                    <th style="width: 100px" class="text-center">Created at</th>
                    <th style="width: 70px"></th>
                </tr>
                </thead>
                <tbody>
                {% for c in codes %}
                    <tr>
                        <td class="font14">{{ c.code }}</td>
                        <td class="font14">{{ c.description }}</td>
                        <td class="text-right font14">$ {{ c.price|floatformat:2|intcomma }}</td>
                        <td class="font12">{{ c.scope }}</td>
                        <td class="text-center font12">{{ c.created_at|date:'m-d-Y' }}</td>
                        <td class="text-center">
                            <a class="tu" href="{% url 'codes' %}?action=edit&id={{ c.id }}" title="Edit"><i class="fa fa-pencil"></i></a>
{#                            {% if not c.has_relations %}#}
                                <a class="tu" href="{% url 'codes' %}?action=delete&id={{ c.id }}" title="Delete" style="margin-left: 0.4em"><i class="fa fa-times"></i></a>
{#                            {% endif %}#}
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="5" class="alert alert-info">
                            <i>There are not work codes in the system. Click in the <strong>+ Add Work Code</strong> button to add your first work code</i>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

            <div class="row">
                <div class="col-sm-12">
                    <a class="btn btn-success" href="{% url 'codes' %}?action=add"><i class="fa fa-plus"></i> Add Work Code</a>
                    <a class="btn btn-warning" href="{% url 'codes' %}?action=print" style="margin-left: 1em"><i class="fa fa-print"></i> Print Work Codes</a>
                </div>
            </div>

        </div>
    </div>
{% endblock %}